### ISSUE TITLE
Build fails on macOS Monterey

### ISSUE THREAD

**Issue by vadimszzz** [nmosier/86x64#6]
```
dflbv@MacBook-Pro build % make             
[  0%] Creating directories for 'mbuild'
[  0%] Performing download step (git clone) for 'mbuild'
Cloning into 'mbuild'...
Already on 'main'
Your branch is up to date with 'origin/main'.
[  0%] Performing update step for 'mbuild'
HEAD is now at 75cb46e External Release v2022.07.28
[  1%] No patch step for 'mbuild'
[  1%] No configure step for 'mbuild'
[  2%] No build step for 'mbuild'
[  2%] No install step for 'mbuild'
[  2%] Completed 'mbuild'
[  2%] Built target mbuild
[  2%] Creating directories for 'xed'
[  2%] Performing download step (git clone) for 'xed'
Cloning into 'xed'...
Already on 'main'
Your branch is up to date with 'origin/main'.
[  3%] Performing update step for 'xed'
HEAD is now at 9fc12ab External Release v2022.10.11
[  3%] No patch step for 'xed'
[  4%] No configure step for 'xed'
[  4%] Performing build step for 'xed'
[CLANG VERSION] 13.1.6
[MBUILD WARNING] Command execution failed. Waiting for remaining jobs and exiting.
[COMMAND     ] PYTHON FN: _remove_libname ;;;; llvm-ar rcv   obj/libxed-ild.a obj/xed-init-ild.o obj/xed-ild-support.o obj/xed-ild.o obj/xed-ild-extension.o obj/xed-chip-features.o obj/xed-isa-set.o obj/xed-chip-modes.o obj/xed-chip-modes-override.o obj/xed-chip-features-table.o obj/xed-ild-disp-l3.o obj/xed-ild-eosz.o obj/xed-ild-easz.o obj/xed-ild-imm-l3.o
[ARGS        ] ['obj/libxed-ild.a']
[ENV         ] some env
[EXIT_STATUS ] 399
[OUTPUT] 
REMOVED obj/libxed-ild.a
[STDERR] 

COMMAND ENCOUNTERD AN EXCEPTION
Traceback (most recent call last):
  File "/Users/dflbv/Downloads/Projects/86x64/build/extern/xed/src/xed/../mbuild/mbuild/util.py", line 1049, in run
    self.sub = subprocess.Popen(cmd_args,
  File "/Users/dflbv/.pyenv/versions/3.9.12/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/dflbv/.pyenv/versions/3.9.12/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'llvm-ar'

ABORT: Library build failed
make[2]: *** [extern/xed/src/xed-stamp/xed-build] Error 1
make[1]: *** [extern/CMakeFiles/xed.dir/all] Error 2
make: *** [all] Error 2
dflbv@MacBook-Pro build % 
```

**Comment by vadimszzz** [comment]
Resolved:

```
brew install nasm
brew install llvm
echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> ~/.zshrc
```
